"""Add destination column to errands

Revision ID: 3a6321f7d5da
Revises: c409a12c7866
Create Date: 2026-02-16 10:44:04.868948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a6321f7d5da'
down_revision = 'c409a12c7866'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('errands', schema=None) as batch_op:
        batch_op.drop_column('destination')

    # ### end Alembic commands ###
